const {chromium}=require('/Users/zhangzhuang/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const origin=process.env.DND_WORKS_ORIGIN||'http://127.0.0.1:8883',base=origin+'/dnd/works/yinhun/',out=__dirname,key='dnd-work-yinhun-reading-v1',coreKey='dnd-codex-reading-v1';
(async()=>{const b=await chromium.launch({executablePath:'/Users/zhangzhuang/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[],failed=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)failed.push(r.url())});
 await p.goto(base);await p.waitForSelector('html.reader-ready');assert.equal(await p.locator('#reader-mode').inputValue(),'intro');assert.equal(await p.locator('.event-card:visible').count(),0);assert.equal(await p.locator('.cast-card:visible').count(),0);assert.equal(await p.locator('.volume-panel:visible').count(),0);assert.equal(await p.locator('.lore-card').count(),4);assert.ok(!(await p.locator('body').innerText()).includes('记忆编织'));
 await p.screenshot({path:out+'/intro-desktop.png',fullPage:true});
 await p.locator('#reader-mode').selectOption('progress');await p.locator('#reader-volume').selectOption('1');assert.equal(await p.locator('.event-card:visible').count(),5);assert.equal(await p.locator('[data-volume-tab="2"]').isDisabled(),true);assert.equal(await p.locator('.volume-panel:visible').count(),1);assert.ok(!(await p.locator('.volume-panel:visible').innerText()).includes('第六卷'));assert.equal(await p.locator('#relations .relationship').isVisible(),false);
 assert.ok(!(await p.locator('body').innerText()).includes('阿拉莎'));await p.locator('#event-search').fill('记忆编织');assert.equal(await p.locator('.event-card:visible').count(),0);await p.locator('#event-search').fill('');
 await p.locator('[data-character="shan-jia"]').first().click();assert.ok(!(await p.locator('#dialog-content').innerText()).includes('城主'));await p.locator('#gallery-next').click();assert.equal(await p.locator('#gallery-title').innerText(),'姿势与换装 1');await p.locator('#dialog-content [data-reader-save="character:shan-jia"]').click();assert.equal(await p.locator('#dialog-content [data-reader-save="character:shan-jia"]').getAttribute('aria-pressed'),'true');await p.keyboard.press('Escape');
 await p.reload();assert.equal(await p.locator('#reader-mode').inputValue(),'progress');await p.locator('[data-reader-resume]').click();assert.equal(await p.locator('#gallery-count').innerText(),'2 / 4');await p.keyboard.press('Escape');
 await p.locator('.event-card:visible').first().locator('summary').click();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('dnd-work-yinhun-reading-v1')).last.kind==='event');await p.locator('.event-card:visible').first().locator('[data-reader-save]').click();
 await p.reload();await p.locator('[data-reader-resume]').click();assert.equal(await p.locator('.event-card:visible').first().evaluate(n=>n.open),true);
 await p.locator('#reader-mode').selectOption('full');assert.equal(await p.locator('.cast-card:visible').count(),12);assert.equal(await p.locator('#history .timeline').isVisible(),true);assert.equal(await p.locator('#relations .relationship').isVisible(),true);assert.ok((await p.locator('.volume-panel:visible').innerText()).includes('第六卷'));
 const galleries=await p.evaluate(()=>Object.keys(GALLERIES));assert.equal(galleries.length,9);
 for(const id of galleries){await p.locator('[data-character="'+id+'"]').first().click();assert.equal(await p.locator('#gallery-count').innerText(),'1 / 4');await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#gallery-count').innerText(),'4 / 4');await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#gallery-count').innerText(),'1 / 4');await p.keyboard.press('Escape')}
 await p.locator('[data-volume-tab="14"]').click();assert.equal(await p.locator('.volume-panel:visible').getAttribute('data-volume'),'14');await p.locator('[data-reader-save="volume:14"]').click();await p.locator('[data-character="wei-kang-ni-ya"]').first().click();await p.locator('#gallery-next').click();await p.locator('[data-reader-save="character:wei-kang-ni-ya"]').click();await p.keyboard.press('Escape');
 await p.locator('#reader-mode').selectOption('progress');await p.locator('#reader-volume').selectOption('1');await p.locator('.reader-shelf summary').click();assert.ok(!(await p.locator('#reader-saved').innerText()).includes('维康'));assert.ok(!(await p.locator('#reader-resume').innerText()).includes('维康'));await p.locator('[data-reader-resume]').click();assert.equal(await p.locator('#detail-dialog').isVisible(),false);assert.ok((await p.locator('#reader-status').innerText()).includes('未解锁'));
 await p.emulateMedia({media:'print'});assert.equal(await p.locator('.event-card:visible').count(),5);assert.equal(await p.locator('.mystery:visible').count(),0);assert.equal(await p.locator('#relations .relationship').isVisible(),false);assert.equal(await p.locator('.volume-panel:visible').count(),1);await p.emulateMedia({media:'screen'});
 // All four comparisons have verified, explicitly scoped source links and reciprocal routes.
 for(const id of ['material','shar','mystra','weave-term']){await p.locator('[data-reader-lore="'+id+'"]').click();assert.ok((await p.locator('#dialog-content').innerText()).includes('官方设定'));assert.ok((await p.locator('#dialog-content').innerText()).includes('小说'));assert.ok((await p.locator('#dialog-content a[target="_blank"]').getAttribute('href')).startsWith('https://www.dndbeyond.com/'));if(id!=='material')assert.equal(await p.locator('#dialog-content [data-reader-lore-source]').isDisabled(),true);await p.keyboard.press('Escape')}
 await p.locator('[data-reader-lore="material"]').click();await p.locator('#dialog-content [data-reader-lore-source]').click();assert.ok((await p.locator('#dialog-content').innerText()).includes('第1卷'));assert.ok(!(await p.locator('#dialog-content').innerText()).includes('第8卷'));await p.keyboard.press('Escape');
 await p.locator('#reader-save-book').click();if(!await p.locator('.reader-shelf').evaluate(n=>n.open))await p.locator('.reader-shelf summary').click();
 await p.evaluate(k=>localStorage.setItem(k,JSON.stringify({saved:['mystra'],recent:[{id:'mystra',mode:'entry',variant:0,time:Date.now()}]})),coreKey);
 const downloadWait=p.waitForEvent('download');await p.locator('[data-reader-export]').click();const download=await downloadWait,exportPath=out+'/backup.json';await download.saveAs(exportPath);const exported=JSON.parse(fs.readFileSync(exportPath));assert.equal(exported.format,'dnd-reading-backup');assert.deepEqual(exported.codex.saved,['mystra']);assert.ok(exported.yinhun.saved.includes('volume:14'));
 const imported={...exported,codex:{saved:['shar','<img src=x>'],recent:[]},yinhun:{...exported.yinhun,mode:'full',volume:14,saved:[...exported.yinhun.saved,'character:NOT-REAL'],last:{kind:'section',id:'javascript:alert(1)'}}};fs.writeFileSync(out+'/import.json',JSON.stringify(imported));await p.locator('#reader-import-file').setInputFiles(out+'/import.json');await p.waitForFunction(()=>document.querySelector('[data-reader-backup-status]').textContent.includes('已合并'));assert.equal(await p.locator('#reader-mode').inputValue(),'progress');assert.equal(await p.locator('#reader-volume').inputValue(),'1');assert.deepEqual(await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).saved,coreKey),['mystra','shar']);assert.ok(!(await p.evaluate(k=>localStorage.getItem(k),key)).includes('NOT-REAL'));
 const before=await p.evaluate(k=>localStorage.getItem(k),key);fs.writeFileSync(out+'/invalid.json','{"format":"wrong"}');await p.locator('#reader-import-file').setInputFiles(out+'/invalid.json');await p.waitForFunction(()=>document.querySelector('[data-reader-backup-status]').textContent.includes('导入失败'));assert.equal(await p.evaluate(k=>localStorage.getItem(k),key),before);
 await p.locator('#reader-clear').click();assert.equal(await p.locator('[data-reader-resume]').count(),0);assert.ok((await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).saved,key)).length>=3);
 await p.goto(origin+'/dnd/#works');assert.equal(await p.locator('[data-save-work]').getAttribute('aria-pressed'),'true');assert.ok((await p.locator('[data-work-reading]').innerText()).includes('第 1 卷'));await p.goto(origin+'/dnd/#overview');assert.equal(await p.locator('#work-reading-desk a').count(),1);assert.equal(await p.locator('[data-reader-export]').count(),1);assert.equal(await p.locator('#saved-count').innerText(),'2');
 for(const id of ['material','shar','mystra','weave-term']){await p.goto(origin+'/dnd/#entry/'+id);await p.locator('a[href$="#lore/'+id+'"]').click();await p.waitForURL(base+'#lore/'+id);assert.equal(await p.locator('#detail-dialog').isVisible(),true);await p.locator('#dialog-content a[href$="#entry/'+id+'"]').click();await p.waitForURL(origin+'/dnd/#entry/'+id);assert.equal(await p.locator('#entry-dialog').isVisible(),true)}
 await p.goto(origin+'/dnd/#art/laeral/2');assert.equal(await p.locator('#art-counter').innerText(),'3 / 4');await p.keyboard.press('Escape');
 // A blocked or corrupt storage area should still permit reading without throwing.
 const corrupt=await b.newPage();corrupt.on('pageerror',e=>errors.push(e.message));await corrupt.goto(base);await corrupt.evaluate(k=>localStorage.setItem(k,'null'),key);await corrupt.reload();assert.equal(await corrupt.locator('#reader-mode').inputValue(),'intro');await corrupt.close();
 const blocked=await b.newPage();blocked.on('pageerror',e=>errors.push(e.message));await blocked.addInitScript(()=>{Storage.prototype.getItem=function(){throw new DOMException('blocked','SecurityError')};Storage.prototype.setItem=function(){throw new DOMException('blocked','SecurityError')}});await blocked.goto(base);assert.ok((await blocked.locator('#reader-storage').textContent()).includes('无法保存'));await blocked.locator('#reader-mode').selectOption('progress');await blocked.locator('#reader-save-book').click();assert.equal(await blocked.locator('.event-card:visible').count(),5);await blocked.locator('.reader-shelf summary').click();const bd=blocked.waitForEvent('download');await blocked.locator('[data-reader-export]').click();const bx=await bd;await bx.saveAs(out+'/blocked-backup.json');const bp=JSON.parse(fs.readFileSync(out+'/blocked-backup.json'));assert.equal(bp.yinhun.mode,'progress');assert.equal(bp.yinhun.book,true);await blocked.close();
 const m=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});m.on('pageerror',e=>errors.push(e.message));await m.goto(base);await m.locator('#reader-mode').selectOption('progress');await m.locator('#reader-volume').selectOption('1');assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await m.locator('#reading').scrollIntoViewIfNeeded();await m.screenshot({path:out+'/reader-mobile.png'});await m.locator('[data-character="shan-jia"]').first().click();await m.locator('#gallery-image').evaluate(x=>x.decode());await m.screenshot({path:out+'/gallery-mobile.png'});const stage=await m.locator('.gallery-stage').boundingBox(),cdp=await m.context().newCDPSession(m);const y=stage.y+Math.min(stage.height/2,130),a=stage.x+stage.width-60,z=stage.x+60;for(const[type,x]of[['touchStart',a],['touchMove',a-20],['touchMove',z],['touchEnd',z]])await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y,radiusX:2,radiusY:2,force:1,id:0}]});await m.waitForFunction(()=>document.getElementById('gallery-count').textContent==='2 / 4');await m.keyboard.press('Escape');await m.setViewportSize({width:320,height:760});assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await m.locator('[data-reader-lore="shar"]').click();assert.ok(await m.locator('#detail-dialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1));
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
 console.log(JSON.stringify({passed:true,origin,spoilers:['intro','progress','full','lowered-limit','search','citations','print'],loreLinks:4,reading:['volume','event','character','gallery-resume','work-favorite','backup-merge','invalid-backup','blocked-storage'],femaleGalleries:9,mobileSwipe:true,narrowScreen:true,jsErrors:errors}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
